package com.kelaniya.sales.model;

import java.util.Objects;

/**
 * Represents a single product sales record.
 * Follows Single Responsibility Principle (SRP) by encapsulating only product data and line calculations.
 */
public class Product {
    private final String productId;
    private final String productName;
    private final String category;
    private final int quantitySold;
    private final double unitPrice;

    public Product(String productId, String productName, String category, int quantitySold, double unitPrice) {
        if (productId == null || productId.trim().isEmpty()) {
            throw new IllegalArgumentException("Product ID cannot be null or empty.");
        }
        if (productName == null || productName.trim().isEmpty()) {
            throw new IllegalArgumentException("Product name cannot be null or empty.");
        }
        if (category == null || category.trim().isEmpty()) {
            throw new IllegalArgumentException("Category cannot be null or empty.");
        }
        if (quantitySold < 0) {
            throw new IllegalArgumentException("Quantity sold cannot be negative: " + quantitySold);
        }
        if (unitPrice < 0) {
            throw new IllegalArgumentException("Unit price cannot be negative: " + unitPrice);
        }

        this.productId = productId.trim();
        this.productName = productName.trim();
        this.category = category.trim();
        this.quantitySold = quantitySold;
        this.unitPrice = unitPrice;
    }

    public String getProductId() {
        return productId;
    }

    public String getProductName() {
        return productName;
    }

    public String getCategory() {
        return category;
    }

    public int getQuantitySold() {
        return quantitySold;
    }

    public double getUnitPrice() {
        return unitPrice;
    }

    /**
     * Computes the total revenue for this product (quantity_sold * unit_price).
     *
     * @return total revenue generated by this product
     */
    public double getTotalRevenue() {
        return quantitySold * unitPrice;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Product product = (Product) o;
        return quantitySold == product.quantitySold &&
                Double.compare(product.unitPrice, unitPrice) == 0 &&
                Objects.equals(productId, product.productId) &&
                Objects.equals(productName, product.productName) &&
                Objects.equals(category, product.category);
    }

    @Override
    public int hashCode() {
        return Objects.hash(productId, productName, category, quantitySold, unitPrice);
    }

    @Override
    public String toString() {
        return String.format("Product{id='%s', name='%s', category='%s', qty=%d, price=%.2f, revenue=%.2f}",
                productId, productName, category, quantitySold, unitPrice, getTotalRevenue());
    }
}
